In [ ]:
from chatsky_llm_autoconfig.metrics.embedder import emb_list

ModuleNotFoundError: No module named 'chatsky_llm_autoconfig'

In [2]:
from langchain_community.cross_encoders.huggingface import HuggingFaceCrossEncoder

In [4]:
%pip install einops

  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Using cached einops-0.8.0-py3-none-any.whl (43 kB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
ce = HuggingFaceCrossEncoder(model_name="jinaai/jina-reranker-v2-base-multilingual", model_kwargs={"device": "cuda:0", "trust_remote_code": True})

/home/peshkichev/.venv/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not installed. Using PyTorch native attention implementation.
flash_attn is not

In [9]:
ce.score([("Welcome to tech support! How can I assist you today?","Thank you for reaching out to tech support! What seems to be the problem today?")])

array([0.53515625], dtype=float32)

In [10]:
ce.score([("How can I assist you today?","What seems to be the problem today?")])

array([0.09960938], dtype=float32)

In [8]:
ce.score([("Hi, I'd like to book a hotel room", "I would like to reserve another room")])

array([0.51171875], dtype=float32)

In [9]:
ce.score([("You've selected a double room for two nights. Is this correct?", "Just to confirm, you're requesting a double room for two nights, correct?")])

array([0.84375], dtype=float32)

In [4]:
ce2 = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3", model_kwargs={"device": "cuda:0"})

In [13]:
ce2.score([("Welcome to tech support! How can I assist you today?","Thank you for reaching out to tech support! What seems to be the problem today?")])

array([0.90209776], dtype=float32)

In [12]:
ce2.score([("Hi, I'd like to book a hotel room", "I would like to reserve another room")])

array([0.6546994], dtype=float32)

In [13]:
ce2.score([("You've selected a double room for two nights. Is this correct?", "Just to confirm, you're requesting a double room for two nights, correct?")])

array([0.9997868], dtype=float32)

In [15]:
ce2.score([("Is the screen flickering issue resolved after updating the drivers?","Please go ahead and update your graphics drivers, then let me know if the flickering continues")])[0]

0.5618778

In [17]:
ce2.score([("Yes, the issue is resolved","Yes, the flickering has stopped")])

array([0.64322704], dtype=float32)

In [15]:
ce2.score([("Is the screen flickering issue resolved after updating the drivers?","Did updating the drivers fix the flickering issue?")])

array([0.9999796], dtype=float32)

In [18]:
ce2.score([("Is the screen flickering issue resolved after updating the drivers? Yes, the issue is resolved","Did updating the drivers fix the flickering issue? Yes, the flickering has stopped")])

array([0.9996846], dtype=float32)

In [19]:
ce2.score([("Is the screen flickering issue resolved after updating the drivers?","Did updating the drivers fix the flickering issue?")])

array([0.9999796], dtype=float32)

In [6]:
ce2.score([("Yes, I've tried restarting","The display is flickering.")])

array([0.00205611], dtype=float32)

In [17]:
ce2.score([("Have you tried restarting your laptop to see if that resolves the flickering? Yes, I've tried restarting it", "Could you please elaborate on the problem you're facing with your laptop? The display is flickering.")])

array([0.978375], dtype=float32)

In [18]:
ce2.score([("Have you tried restarting your laptop to see if that resolves the flickering?", "Could you please elaborate on the problem you're facing with your laptop?")])

array([0.04272561], dtype=float32)

In [19]:
ce2.score([("Have you tried restarting your laptop to see if that resolves the flickering? Have you tried restarting your laptop to see if that resolves the flickering? Yes, I've tried restarting it", "Could you please elaborate on the problem you're facing with your laptop? Could you please elaborate on the problem you're facing with your laptop? The display is flickering.")])

array([0.93438506], dtype=float32)

In [7]:
ce2.score([("How can I assist you today?","Is there anything else I can assist you with today?")])

array([0.9999378], dtype=float32)

In [14]:
ce2.score([("Welcome to our car service center!","Thank you!")])

array([0.04039782], dtype=float32)

In [16]:
ce2.score([("Welcome to tech support! How can I assist you today?","Thank you for reaching out to tech support! What seems to be the problem today?")])

array([0.90209776], dtype=float32)

In [8]:
ce.score([("How can I assist you today?","Is there anything else I can assist you with today?")])

array([0.56640625], dtype=float32)

In [1]:
%pip show networkx

Name: networkx
Version: 3.3
Summary: Python package for creating and manipulating graphs and networks
Home-page: https://networkx.org/
Author: 
Author-email: Aric Hagberg <hagberg@lanl.gov>
License: 
Location: /cephfs/home/peshkichev/.venv/lib/python3.10/site-packages
Requires: 
Required-by: python-louvain, torch
Note: you may need to restart the kernel to use updated packages.


In [4]:
import copy

In [5]:
test = {
              "edges": [
            {
              "source": 1,
              "target": 2,
              "utterances": [
                "Hi, I'm having trouble with my laptop"
              ]
            },
            {
              "source": 2,
              "target": 3,
              "utterances": [
                "The screen is flickering"
              ]
            },
            {
              "source": 3,
              "target": 4,
              "utterances": [
                "Yes, I've tried restarting it"
              ]
            },
            {
              "source": 4,
              "target": 5,
              "utterances": [
                "No, I haven't updated the drivers"
              ]
            },
            {
              "source": 5,
              "target": 6,
              "utterances": [
                "Sure, I'll update the drivers now"
              ]
            },
            {
              "source": 6,
              "target": 7,
              "utterances": [
                "Yes, the issue is resolved"
              ]
            },
            {
              "source": 7,
              "target": 2,
              "utterances": [
                "Actually, there's another issue"
              ]
            }
          ],
          "nodes": [
            {
              "id": 1,
              "label": "welcome",
              "is_start": True,
              "utterances": [
                "Welcome to tech support! How can I assist you today?"
              ]
            },
            {
              "id": 2,
              "label": "ask_issue",
              "is_start": False,
              "utterances": [
                "Can you describe the issue you're experiencing with your laptop?"
              ]
            },
            {
              "id": 3,
              "label": "troubleshoot_restart",
              "is_start": False,
              "utterances": [
                "Have you tried restarting your laptop to see if that resolves the flickering?"
              ]
            },
            {
              "id": 4,
              "label": "ask_drivers",
              "is_start": False,
              "utterances": [
                "Have you checked if your graphics drivers are up to date?"
              ]
            },
            {
              "id": 5,
              "label": "guide_update",
              "is_start": False,
              "utterances": [
                "Please update your graphics drivers and let me know if the issue persists."
              ]
            },
            {
              "id": 6,
              "label": "confirm_resolution",
              "is_start": False,
              "utterances": [
                "Is the screen flickering issue resolved after updating the drivers?"
              ]
            },
            {
              "id": 7,
              "label": "additional_help",
              "is_start": False,
              "utterances": [
                "Great to hear! Is there anything else I can help you with?"
              ]
            }
          ]
        }

In [6]:
test

{'edges': [{'source': 1,
   'target': 2,
   'utterances': ["Hi, I'm having trouble with my laptop"]},
  {'source': 2, 'target': 3, 'utterances': ['The screen is flickering']},
  {'source': 3, 'target': 4, 'utterances': ["Yes, I've tried restarting it"]},
  {'source': 4,
   'target': 5,
   'utterances': ["No, I haven't updated the drivers"]},
  {'source': 5,
   'target': 6,
   'utterances': ["Sure, I'll update the drivers now"]},
  {'source': 6, 'target': 7, 'utterances': ['Yes, the issue is resolved']},
  {'source': 7,
   'target': 2,
   'utterances': ["Actually, there's another issue"]}],
 'nodes': [{'id': 1,
   'label': 'welcome',
   'is_start': True,
   'utterances': ['Welcome to tech support! How can I assist you today?']},
  {'id': 2,
   'label': 'ask_issue',
   'is_start': False,
   'utterances': ["Can you describe the issue you're experiencing with your laptop?"]},
  {'id': 3,
   'label': 'troubleshoot_restart',
   'is_start': False,
   'utterances': ['Have you tried restarting 

In [ ]:
def graph2comparable(graph_dict: dict) -> dict:
    new_dict = copy.deepcopy(graph_dict)
    new_edges = []
    for edge in new_dict["edges"]:
        edge["utterances"] = next(node for node in graph_dict["nodes"] if node["id"] == edge["source"])["utterances"][0] + edge["utterances"]
        new_edges.append(edge)
    new_dict["edges"] = new_edges
    return new_dict

In [16]:
def graph2comparable(graph_dict: dict) -> dict:
    new_dict = copy.deepcopy(graph_dict)
    new_edges = []
    for edge in new_dict["edges"]:
        edge["utterances"] = [next(node for node in graph_dict["nodes"] if node["id"] == edge["source"])["utterances"][0] + " " + edge["utterances"][0]]
        new_edges.append(edge)
    new_dict["edges"] = new_edges
    return new_dict

In [17]:
graph2comparable(test)

{'edges': [{'source': 1,
   'target': 2,
   'utterances': ["Welcome to tech support! How can I assist you today? Hi, I'm having trouble with my laptop"]},
  {'source': 2,
   'target': 3,
   'utterances': ["Can you describe the issue you're experiencing with your laptop? The screen is flickering"]},
  {'source': 3,
   'target': 4,
   'utterances': ["Have you tried restarting your laptop to see if that resolves the flickering? Yes, I've tried restarting it"]},
  {'source': 4,
   'target': 5,
   'utterances': ["Have you checked if your graphics drivers are up to date? No, I haven't updated the drivers"]},
  {'source': 5,
   'target': 6,
   'utterances': ["Please update your graphics drivers and let me know if the issue persists. Sure, I'll update the drivers now"]},
  {'source': 6,
   'target': 7,
   'utterances': ['Is the screen flickering issue resolved after updating the drivers? Yes, the issue is resolved']},
  {'source': 7,
   'target': 2,
   'utterances': ["Great to hear! Is there a

In [2]:
import json

In [3]:
def read_json(path):
    with open(path, mode="r") as file:
        data = file.read()
    return json.loads(data)

In [14]:
saved = read_json("../autometrics/test_data/saved.json")

In [19]:
saved['o1-mini']['fourth_graph_generation_prompt']

[{'booking a hotel room': [{'edges': [{'source': 1,
      'target': 2,
      'utterances': ['Hello, I want to reserve a hotel room.']},
     {'source': 2,
      'target': 3,
      'utterances': ['A double room for a two-night stay, please.']},
     {'source': 3, 'target': 4, 'utterances': ["Yes, that's correct."]},
     {'source': 4,
      'target': 5,
      'utterances': ['Here is my credit card information.']},
     {'source': 5,
      'target': 2,
      'utterances': ['I would like to reserve another room.']}],
    'nodes': [{'id': 1,
      'label': 'start',
      'is_start': True,
      'utterances': ['Thank you for reaching out to our hotel booking service! How can I help you today?']},
     {'id': 2,
      'label': 'ask_room_type',
      'is_start': False,
      'utterances': ['What kind of room are you interested in booking?']},
     {'id': 3,
      'label': 'confirm_reservation',
      'is_start': False,
      'utterances': ['So, you would like to reserve a double room for two 

In [20]:
second = saved['o1-mini']['fourth_graph_generation_prompt'][0]['booking a hotel room'][0]

In [21]:
second

{'edges': [{'source': 1,
   'target': 2,
   'utterances': ['Hello, I want to reserve a hotel room.']},
  {'source': 2,
   'target': 3,
   'utterances': ['A double room for a two-night stay, please.']},
  {'source': 3, 'target': 4, 'utterances': ["Yes, that's correct."]},
  {'source': 4,
   'target': 5,
   'utterances': ['Here is my credit card information.']},
  {'source': 5,
   'target': 2,
   'utterances': ['I would like to reserve another room.']}],
 'nodes': [{'id': 1,
   'label': 'start',
   'is_start': True,
   'utterances': ['Thank you for reaching out to our hotel booking service! How can I help you today?']},
  {'id': 2,
   'label': 'ask_room_type',
   'is_start': False,
   'utterances': ['What kind of room are you interested in booking?']},
  {'id': 3,
   'label': 'confirm_reservation',
   'is_start': False,
   'utterances': ['So, you would like to reserve a double room for two nights. Is that right?']},
  {'id': 4,
   'label': 'ask_payment_details',
   'is_start': False,
   

In [22]:
nodes2 = [n['utterances'][0]+" "+e['utterances'][0] for n,e in zip(second['nodes'],second['edges'])]

In [23]:
nodes2

['Thank you for reaching out to our hotel booking service! How can I help you today? Hello, I want to reserve a hotel room.',
 'What kind of room are you interested in booking? A double room for a two-night stay, please.',
 "So, you would like to reserve a double room for two nights. Is that right? Yes, that's correct.",
 'Fantastic! Please share your payment details to finalize the booking. Here is my credit card information.',
 'Thank you for your reservation! Would you like to book an additional room? I would like to reserve another room.']

In [5]:
dialogue_to_graph = read_json("../autometrics/test_data/dialogue_dataset_9_topics_3.json")

In [ ]:
dialogue_to_graph[0]['graph']['edges']

[{'source': 1,
  'target': 2,
  'utterances': ["Hi, I'd like to book a hotel room"]},
 {'source': 2,
  'target': 3,
  'utterances': ['A double room for two nights, please']},
 {'source': 3, 'target': 4, 'utterances': ["Yes, that's correct"]},
 {'source': 4,
  'target': 5,
  'utterances': ["Here's my credit card information"]},
 {'source': 5, 'target': 2, 'utterances': ["I'd like to book another room"]}]

In [12]:
nodes = [n['utterances'][0]+" "+e['utterances'][0] for n,e in zip(dialogue_to_graph[0]['graph']['nodes'],dialogue_to_graph[0]['graph']['edges'])]

In [13]:
nodes

["Welcome to our hotel booking service! How can I assist you today? Hi, I'd like to book a hotel room",
 'What type of room would you like to book? A double room for two nights, please',
 "You've selected a double room for two nights. Is this correct? Yes, that's correct",
 "Great! Please provide your payment details to proceed. Here's my credit card information",
 "Thank you for your booking! Would you like to book another room? I'd like to book another room"]

In [28]:
from sentence_transformers import SentenceTransformer

/home/peshkichev/.venv/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [26]:

embedding = {}

In [24]:
def get_embedding(golden: list[str], generated: list[str], emb_name: str, device: str):

    if emb_name not in embedding:
        embedding[emb_name] = SentenceTransformer(emb_name,device=device)
 
    golden_vectors = embedding[emb_name].encode(golden, normalize_embeddings=True)
    generated_vectors = embedding[emb_name].encode(generated, normalize_embeddings=True)
    similarities = generated_vectors @ golden_vectors.T
    return similarities

In [30]:
a = get_embedding(nodes, nodes2, "BAAI/bge-m3", "cuda:0")

In [33]:
a

array([[0.94180244, 0.6909936 , 0.5869953 , 0.576563  , 0.8095979 ],
       [0.7253463 , 0.95404375, 0.768647  , 0.53807896, 0.7475831 ],
       [0.62819135, 0.81138206, 0.93451023, 0.5362539 , 0.68607736],
       [0.6325436 , 0.6072511 , 0.6007808 , 0.9133621 , 0.6760294 ],
       [0.7797273 , 0.73002976, 0.6411421 , 0.60386   , 0.9629208 ]],
      dtype=float32)

In [31]:
import numpy as np

In [62]:
np.vstack(([1,2],[2,3]))

array([[1, 2],
       [2, 3]])

In [63]:
s = a.shape[0]
diag = np.diag(a,0)
for n in range(1,s):
    diag = np.vstack([diag,np.concatenate((np.diag(a,n),np.diag(a,n-s)))])
diag

array([[0.94180244, 0.95404375, 0.93451023, 0.9133621 , 0.9629208 ],
       [0.6909936 , 0.768647  , 0.5362539 , 0.6760294 , 0.7797273 ],
       [0.5869953 , 0.53807896, 0.68607736, 0.6325436 , 0.73002976],
       [0.576563  , 0.7475831 , 0.62819135, 0.6072511 , 0.6411421 ],
       [0.8095979 , 0.7253463 , 0.81138206, 0.6007808 , 0.60386   ]],
      dtype=float32)

In [65]:
sums = np.sum(diag,axis=1)

In [66]:
np.argmax(sums)

0

In [6]:
graph_1 = dialogue_to_graph[0]['graph']
graph_1

{'edges': [{'source': 1,
   'target': 2,
   'utterances': ["Hi, I'd like to book a hotel room"]},
  {'source': 2,
   'target': 3,
   'utterances': ['A double room for two nights, please']},
  {'source': 3, 'target': 4, 'utterances': ["Yes, that's correct"]},
  {'source': 4,
   'target': 5,
   'utterances': ["Here's my credit card information"]},
  {'source': 5, 'target': 2, 'utterances': ["I'd like to book another room"]}],
 'nodes': [{'id': 1,
   'label': 'welcome',
   'is_start': True,
   'utterances': ['Welcome to our hotel booking service! How can I assist you today?']},
  {'id': 2,
   'label': 'ask_room_type',
   'is_start': False,
   'utterances': ['What type of room would you like to book?']},
  {'id': 3,
   'label': 'confirm_details',
   'is_start': False,
   'utterances': ["You've selected a double room for two nights. Is this correct?"]},
  {'id': 4,
   'label': 'payment',
   'is_start': False,
   'utterances': ['Great! Please provide your payment details to proceed.']},
  {'

In [11]:
node_0 = [node for node in graph_1["nodes"] if node["is_start"]][0]

In [12]:
node_0

{'id': 1,
 'label': 'welcome',
 'is_start': True,
 'utterances': ['Welcome to our hotel booking service! How can I assist you today?']}

In [15]:
import numpy as np

In [18]:
np.array([1,2]) @ np.array([[1,1],[1,2]])

array([3, 5])

In [24]:
a = np.array([1,1,3,2])
a

array([1, 1, 3, 2])

In [25]:
a.reshape(2,2)

array([[1, 1],
       [3, 2]])

In [23]:
a[1]

array([3, 2])

In [13]:
res = []
node = [node for node in graph_1["nodes"] if node["is_start"]][0]
for idx in range(len(graph_1["nodes"])):
    edge = [e for e in graph_1['edges'] if e['source']==node["id"]][0]
    res.append(node['utterances'][0]+" "+edge['utterances'][0])
    node = [node for node in graph_1["nodes"] if node["id"]==edge['target']][0] 
res

["Welcome to our hotel booking service! How can I assist you today? Hi, I'd like to book a hotel room",
 'What type of room would you like to book? A double room for two nights, please',
 "You've selected a double room for two nights. Is this correct? Yes, that's correct",
 "Great! Please provide your payment details to proceed. Here's my credit card information",
 "Thank you for your booking! Would you like to book another room? I'd like to book another room"]

In [8]:
res = []
for node in graph_1["nodes"]:
    edge = [e for e in graph_1['edges'] if e['source']==node["id"]][0]
    res.append(node['utterances'][0]+" "+edge['utterances'][0])
res

["Welcome to our hotel booking service! How can I assist you today? Hi, I'd like to book a hotel room",
 'What type of room would you like to book? A double room for two nights, please',
 "You've selected a double room for two nights. Is this correct? Yes, that's correct",
 "Great! Please provide your payment details to proceed. Here's my credit card information",
 "Thank you for your booking! Would you like to book another room? I'd like to book another room"]

In [ ]:
def graph2list(graph: dict) -> list:
    return [n['utterances'][0]+" "+e['utterances'][0] for n,e in zip(graph['nodes'], graph['edges'])]

In [72]:
l[2:]+l[:2]

[3, 1, 2]

In [73]:
def get_diagonal(graph, i):
    result = {}
    result['edges'] = graph['edges'][i:] + graph['edges'][:i]
    result['nodes'] = graph['nodes'][i:] + graph['nodes'][:i]
    return result

In [74]:
get_diagonal(graph_1,1)

{'edges': [{'source': 2,
   'target': 3,
   'utterances': ['A double room for two nights, please']},
  {'source': 3, 'target': 4, 'utterances': ["Yes, that's correct"]},
  {'source': 4,
   'target': 5,
   'utterances': ["Here's my credit card information"]},
  {'source': 5, 'target': 2, 'utterances': ["I'd like to book another room"]},
  {'source': 1,
   'target': 2,
   'utterances': ["Hi, I'd like to book a hotel room"]}],
 'nodes': [{'id': 2,
   'label': 'ask_room_type',
   'is_start': False,
   'utterances': ['What type of room would you like to book?']},
  {'id': 3,
   'label': 'confirm_details',
   'is_start': False,
   'utterances': ["You've selected a double room for two nights. Is this correct?"]},
  {'id': 4,
   'label': 'payment',
   'is_start': False,
   'utterances': ['Great! Please provide your payment details to proceed.']},
  {'id': 5,
   'label': 'completed',
   'is_start': False,
   'utterances': ['Thank you for your booking! Would you like to book another room?']},
  

In [4]:
gym = read_json("../autometrics/test_data/short_gym.json")

In [1]:
from datasets import load_dataset

In [3]:
data = load_dataset("askatasuna/CycleDialogueGraphs_v1", token="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")

README.md:   0%|          | 0.00/2.68k [00:00<?, ?B/s]

cycle_graphs_v1.parquet:   0%|          | 0.00/18.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/10 [00:00<?, ? examples/s]

In [1]:
str(data['train'][0])

NameError: name 'data' is not defined